# Generated by Django 4.0.4 on 2022-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_1st', models.CharField(max_length=255)),
                ('mon_1st_sub', models.CharField(max_length=255)),
                ('mon_2st', models.CharField(max_length=255)),
                ('mon_2st_sub', models.CharField(max_length=255)),
                ('mon_3st', models.CharField(max_length=255)),
                ('mon_3st_sub', models.CharField(max_length=255)),
                ('tue_1st', models.CharField(max_length=255)),
                ('tue_1st_sub', models.CharField(max_length=255)),
                ('tue_2st', models.CharField(max_length=255)),
                ('tue_2st_sub', models.CharField(max_length=255)),
                ('tue_3st', models.CharField(max_length=255)),
                ('tue_3st_sub', models.CharField(max_length=255)),
                ('wed_1st', models.CharField(max_length=255)),
                ('wed_1st_sub', models.CharField(max_length=255)),
                ('wed_2st', models.CharField(max_length=255)),
                ('wed_2st_sub', models.CharField(max_length=255)),
                ('wed_3st', models.CharField(max_length=255)),
                ('wed_3st_sub', models.CharField(max_length=255)),
                ('thu_1st', models.CharField(max_length=255)),
                ('thu_1st_sub', models.CharField(max_length=255)),
                ('thu_2st', models.CharField(max_length=255)),
                ('thu_2st_sub', models.CharField(max_length=255)),
                ('thu_3st', models.CharField(max_length=255)),
                ('thu_3st_sub', models.CharField(max_length=255)),
                ('fri_1st', models.CharField(max_length=255)),
                ('fri_1st_sub', models.CharField(max_length=255)),
                ('fri_2st', models.CharField(max_length=255)),
                ('fri_2st_sub', models.CharField(max_length=255)),
                ('fri_3st', models.CharField(max_length=255)),
                ('fri_3st_sub', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='app.classdb')),
            ],
        ),
    ]
